# Generated by Django 3.0.3 on 2020-02-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
    ]
