# Generated by Django 3.0.3 on 2020-02-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
